//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartWithUs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string Report_ID { get; set; }
        public string Company_ID { get; set; }
        public string Enterpreneur_ID { get; set; }
        public string Investor_ID { get; set; }
        public string Payment_ID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Enterpreneur Enterpreneur { get; set; }
        public virtual Investor Investor { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
